### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by ibroh24** [saheedibrahim/goods-delivery#1]
The whole code files are fine. I can see that you created models that transport tables information to db.
However, the code needs the following refactor:
1. Organization
    * DB and Authorization needed to be in a folder separately.
    * Models are also to be in a separate folder as well, organize everything in a folder.
    * A Controller folder is also needed as well, for getting your datas, it could be in functional approach or class and object ways.

2. Repetitions 
    * There are many repetitions in your code, the programmer goal is to always minimize/optimize code in other not to repeat single functionality twice. 
    * Don't Repeat Yourself! Any code that you wrote twice with little difference can be turned to function and distinguish the differences with parameters.

**Comment by saheedibrahim** [comment]
ok, jazakumuLlahu khairan. I have reorganized it into folder but assist me in checking if the arrangement is ok so that I will use it when rewriting this project using OOP. Although I didn't edit the code but a few amendments to suit the rearrangement.
Also, I am not through yet but intend to complete it using OOP (classes).

**Comment by saheedibrahim** [comment]
ok, jazakumuLlahu khairan. I have reorganized it into folder but assist me in checking if the arrangement is ok so that I will use it when rewriting this project using OOP. Although I didn't edit the code but a few amendments to suit the rearrangement.
Also, I am not through with it yet but intend to complete it using OOP (classes).

**Comment by saheedibrahim** [comment]
ok, jazakumuLlahu khairan. I have reorganized it into folder but assist me in checking if the arrangement is ok so that I will use it when rewriting this project using OOP. Although I didn't edit the code but a few amendments to suit the rearrangement.
Also, I am not through yet but intend to complete it using OOP (classes).

**Comment by ibroh24** [comment]
Cool
